GRANT SELECT ON {{MYSQL_DATEBASE}}.* TO '{{MYSQL_USERNAME}}'@'%' IDENTIFIED BY '{{MYSQL_PASSWORD}}';

GRANT ALL on {{MYSQL_DATEBASE}}.radacct TO '{{MYSQL_USERNAME}}'@'%';
GRANT ALL on {{MYSQL_DATEBASE}}.radpostauth TO '{{MYSQL_USERNAME}}'@'%';
