MYSQL_DATEBASE=${MYSQL_DATEBASE:-"radius"}
MYSQL_HOST=${MYSQL_HOST:-"mysql"}
MYSQL_USERNAME=${MYSQL_USERNAME:-"radius"}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-"radpass"}
MYSQL_PORT=${MYSQL_PORT:-"3306"}
RADIUS_KEY=${RADIUS_KEY:-"testing123"}
RADIUS_LISTEN=${RADIUS_LISTEN:-"0.0.0.0"}
