#!/bin/bash
apk update
apk add freeradius-mysql mariadb-client acct
apk add --virtual build-dependencies openssl make
cd /etc/raddb/certs
./bootstrap && make
apk del --purge build-dependencies
rm -rf /var/cache/apk/*
